name: TeamSmith
version: ${project.version}
main: com.listjonas.teamSmith.TeamSmith
api-version: '1.21'
authors:
  - Jonas List
website: https://www.listjonas.com
description: A plugin for managing teams in Minecraft.
