name: TeamSmith
version: 1.0.0
main: com.listjonas.teamSmith.TeamSmith
api-version: 1.17 # Or your target server version, e.g., 1.18, 1.19, 1.20
author: YourName
description: A plugin to manage teams with prefixes.
commands:
  team:
    description: Main command for TeamSmith plugin.
    usage: /team <subcommand> [args]
    aliases: [ts, myteam]
    subcommands:
      sethome: Set the team home location (OWNER/MANAGER)
      delhome: Delete the team home location (OWNER/MANAGER)
      home: Teleport to the team home
      setwarp: Set a named team warp (OWNER/MANAGER, max 3)
      delwarp: Delete a named team warp (OWNER/MANAGER)
      warp: Teleport to a named team warp (3 min cooldown)